# Generated by Django 3.1.5 on 2021-01-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='button_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
